# Generated by Django 5.1.1 on 2025-06-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_orden_nombre_cliente_orden_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
    ]
